### ISSUE TITLE
Brainstorm para indicações de ideias em projetos de software

### ISSUE THREAD

**Issue by radamesp7** [radamesp7/AbexII_G3_2024#1]
O brainstorming se aplica a disciplina de aprendizado baseado em experiências, onde os alunos em grupos indicam o que pode ser uma ideia de problema que possa ser solucionado com o desenvolvimento de um aplicativo de software e que tem uma finalidade prática. O brainstoriming deve gerar ideias entre os membros do grupo e precisa que se use como base o github para que possam trabalhar como grupo de trabalho e registrar as ideias conforme forem gerando as mesmas.

 Lista de Ideias:

**Comment by monicatissiani** [comment]
Qualquer coisa ...

**Comment by radamesp7** [comment]
Qualquer outra coisa

**Comment by matheusperin161** [comment]
Aplicativo com a funcionalidade de monitorar o transporte publico, com o intuito de saber se o ônibus esta chegando no seu ponto.
Uma aba onde mostrara as linhas do transporte, para saber qual devera pegar para o local desejado.
Aba de recarregamento de cartão e desbloqueio para a modalidade estudante e idosos.
Emitir um alerta de atraso(devido ao transito ou problema no ônibus)
Estimativa de chegada do ônibus. 
Estimativa de pessoas no transporte.
Avaliação do motorista.

**Comment by diogoBenedet** [comment]
Aplicativo com a funcionalidade de ajudar você a escolher a unidade de saúde ideal para seu atendimento
- Informaria a quantidade de pessoas nesta U.B.S
- Com base nos seus sintomas, mostraria qual a melhor decisão: hospital, posto de saúde ou UPA
- Tempo de Espera Estimado: Exibir estimativas de tempo de espera para ser atendido
- Informar sobre quais especialidades médicas estão disponíveis em cada unidade de saúde
-  Disponibilizar informações educativas sobre como lidar com sintomas comuns e quando buscar atendimento
-  Permitir que os usuários avaliem e deixem comentários sobre suas experiências em diferentes unidades de saúde

**Comment by Avila-stack** [comment]
Alocação ou  venda de Imoveis
* varias empresas pode colocar seus imoveis
* tem a opção de localizar imoveis na redondezas 
* mostra todas a informaçoes do imovel (tanto de esta para venda quando para locação)
* o usuario consegue colocar quanto tempo usará o imovel e se no final pretende renovar
* pagamentos podem ser pelo aplicativo, como pix, cartão, boletos.
* o usuario consegue avaliar o imovel (anonimamente opcional)
* mostra todas as regras do imovel e do condominio (se tiver)

**Comment by diogoBenedet** [comment]
1-Aplicativo com a funcionalidade de ajudar você a escolher a unidade de saúde ideal para seu atendimento
2-Aplicativo de reporte de problemas urbanos:
3-Aplicativo de vagas deestacionamento(Integração com Rizzo Park)
4-Aplicativo de adoção e cuidado de Animais
5-Aplicativo de  mercado local que conecta consumidores a produtores locais de alimentos
6-Aplicativo de agenda de eventos de Chapecó
7- Aplicativo de sugestões para a prefeitura
8-Aplicativo de compartilhamento de caronas
9-aplicativo de avisos de obras e interdições

**Comment by matheusperin161** [comment]
Aplicativo para recolhimento de lixo
- Permite ao usuário tirar uma foto do problema (lixo na rua ou lixeira cheia) e usa o GPS para marcar a localização exata.
- O usuário pode adicionar uma breve descrição do problema.
Categoria: Escolher entre categorias como "Lixeira Cheia", "Lixo Espalhado", "Reciclagem Necessária", etc.

**Comment by matheusperin161** [comment]
Aplicativo de segurança pessoal, facilitando e deixando a pessoa mais segura enquanto anda á noite.

- Permite que usuários compartilhem sua localização em tempo real com contatos de confiança enquanto caminham.
- Botão de emergência que notifica contatos pré-definidos e autoridades locais em caso de emergência.
- Sugere rotas mais seguras baseadas em dados de crime e feedback da comunidade.
- Aba onde os usuários podem compartilhar dicas de segurança e relatar incidentes.
